### ISSUE TITLE
adguard.0: cannot find start file!

### ISSUE THREAD

**Issue by Comotio82** [o0shojo0o/ioBroker.adguard#5]
**Describe the bug**  
Adapter does not start.

**To Reproduce**  
1. I installed latest version 0.0.4 from github. 
2. I created an instance and do an upload. 
3. If filled in the ip adress and login corretly. 

**Expected behavior**  

**Screenshots & Logfiles**  

host.ioBroker | 2021-07-19 11:33:16.325 | error | startInstance adguard.0: cannot find start file!

**Versions:**  
![Unbenannt](https://user-images.githubusercontent.com/43888945/126139855-f3d33016-2596-4a66-8467-301ad22c9904.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/43888945/126139864-dabe0065-2c39-49f5-bc9f-b4344f886139.JPG)
![3](https://user-images.githubusercontent.com/43888945/126139868-4a6438e6-9721-42bc-852d-1ca11a1018e7.JPG)

**Comment by o0shojo0o** [comment]
Hi, the problem is that this adapter is written in TypeScript.
But the current JS controller from stable can't launch TypeScript adpater directly from Git repository.

So you are left with two options: 
1. install the JS controller from the beta branch 
2. wait until the AdGuard adapter is included in the ioBroker repo.
